name: Fetch Latest YouTube Chat

on:
  schedule:
    - cron: '0 * * * *'  # 毎時0分に実行（JSTだと+9時間）
  workflow_dispatch:  # 手動実行も可能

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Python をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 依存関係をインストール
        run: |
          python -m pip install --upgrade pip
          pip install chat-downloader requests

      - name: チャットを取得して保存
        env:
          API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          python fetch_latest_chat.py

      - name: 出力ファイルをコミットしてプッシュ
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git pull --rebase
          git add latest_chat_filtered.json
          git commit -m "Update latest chat JSON" || echo "No changes to commit"
          git push
